# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ffcbdb55-559c-45a3-98b0-305657091925";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d2440095-cbf9-4573-aed1-98c83f9baa0c".device = "/dev/disk/by-uuid/d2440095-cbf9-4573-aed1-98c83f9baa0c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/342F-0C46";
      fsType = "vfat";
    };

  swapDevices =[ 
    { device = "/dev/disk/by-uuid/3c860f05-e3f0-43ef-a32b-8abd7db455dc"; }
  ];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s5.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  hardware.parallels.enable = true;
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [ "prl-tools" ];
}
